services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"

  api:
    build: ./services/api
    container_name: api-service
    ports:
      - "8000:8000"
    depends_on:
      - mqtt

  vision:
    build: ./services/vision
    container_name: vision-service
    environment:
      VISION_ENV: "dev"
      VISION_MQTT_HOST: "mqtt"
      VISION_MQTT_PORT: "1883"
      VISION_FRAME_SOURCE: "stream"
      VISION_HAL_STREAM_URL: "http://hal:8080/camera/stream"
      VISION_HAL_SNAPSHOT_URL: "http://hal:8080/camera/frame"
      VISION_DEBUG_VIDEO_ENABLE: "true"
    ports:
      - "8090:8090"
    depends_on:
      - mqtt
      - hal

  #decision:
   # build: ./services/decision
    #container_name: decision-service
    #depends_on:
     # - mqtt

  hal:
    build: ./services/hal
    container_name: hal-service
    environment:
      HAL_ENV: "dev"
      HAL_MQTT_HOST: "mqtt"
      HAL_MQTT_PORT: "1883"
      HAL_SERVO_PROVIDER: "mock"
      HAL_CAMERA_PROVIDER: "opencv"
      HAL_CAMERA_DEVICE_INDEX: "0"
      HAL_GPIO_PROVIDER: "mock"
      HAL_PWM_PROVIDER: "mock"
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8080:8080"
    depends_on:
      - mqtt

  #frontend:
   # build: ./services/frontend
    #container_name: frontend
    #ports:
     # - "5173:5173"

networks:
  default:
    name: fatigue-monitor-network
